[supabase]
url = "https://uyvjndfwssdeogychkqf.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5dmpuZGZ3c3NkZW9neWNoa3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0MzA0NjAsImV4cCI6MjA4NzAwNjQ2MH0.GEPMr6j7uS6gOs6qJDMy5Z8e0PiXnNzEQgcSVTDT-4Y"
